version: '3.8'

services:
  postgres:
    image: postgres:14.13
    container_name: postgres-db
    environment:
      POSTGRES_DB: group
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./scripts/create_company_schema_function.sql:/docker-entrypoint-initdb.d/01-create_company_schema_function.sql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  openldap:
    image: osixia/openldap:1.5.0
    container_name: local-openldap
    environment:
      LDAP_ORGANISATION: "MyCompany"
      LDAP_DOMAIN: "mycompany.com"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"     # LDAP
      - "636:636"     # LDAPS（如不需要可去掉）
    volumes:
      - ./ldap_data:/var/lib/ldap
      - ./ldap_config:/etc/ldap/slapd.d
    networks:
      - app-network
  
  phpldapadmin:
    image: dinkel/phpldapadmin
    ports:
      - "8085:80"
    environment:
      LDAP_SERVER_HOST: openldap
      LDAP_SERVER_PORT: 389
    networks:
      - app-network
    depends_on:
      - openldap
      
  server:
    build: ./server
    ports:
      - "8080:8080"
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=dev,ldap
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/group
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_LDAP_URLS=ldap://openldap:389
      - SPRING_LDAP_USERNAME=cn=admin,dc=mycompany,dc=com
      - SPRING_LDAP_PASSWORD=admin
      - SPRING_LDAP_BASE=dc=mycompany,dc=com
      # 系统初始化配置
      - SYSTEM_INITIALIZER_ENABLED=true
      - DEFAULT_COMPANY_NAME=public
      - DEFAULT_COMPANY_SCHEMA=public
      - DEFAULT_COMPANY_ACTIVE=true
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PHONE_NUMBER=1234567890
      - ADMIN_PASSWORD=12345
    volumes:
      - ./logs/app:/app/logs
    networks:
      - app-network
    depends_on:
      - postgres
      - openldap

networks:
  app-network:
    driver: bridge