version: '3.8'
services:

  postgres:
    container_name: database
    image: postgres:14.13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=group
    ports:
      - 5432:5432
    volumes:
      - ./logs/postgres:/etc/logs/postgres
      - ./logs/postgres:/var/log/postgres
      - ./data/postgres:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - ./logs/rabbitmq:/var/log/rabbitmq

