#version: '3.8'
services:
  compileapk:
    container_name: compileApk
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app  # 将当前目录挂载到容器的 /app 目录
#    command: tail -f /dev/null  # 保持容器运行，不会退出
#    stdin_open: true  # 允许进入容器
#    tty: true  # 保持伪终端，允许交互式使用

    environment:
#      - JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 # 设置 Java 环境变量（如果有其他配置环境变量需要添加）
      - JAVA_HOME=/usr/lib/jvm/graalvm # 设置 Java 环境变量（如果有其他配置环境变量需要添加）
      - GRAALVM_HOME=/usr/lib/jvm/graalvm  # 设置 Java 环境变量（如果有其他配置环境变量需要添加）
      - PATH=/usr/lib/jvm/graalvm/bin:$PATH  # 确保能使用 GraalVM 和相关工具

  postgres:
    container_name: database
    image: postgres:14.13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=group
    ports:
      - 5432:5432
    volumes:
      - ./logs/postgres:/etc/logs/postgres
      - ./logs/postgres:/var/log/postgres
      - ./data/postgres:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - ./logs/rabbitmq:/var/log/rabbitmq

