im:
  server:
    rest:
      host: ${SERVER_HOST:http://192.168.3.22:8080}
    connect:
      host: ${CONNECT_HOST:192.168.3.22}
      port: 8088
logging:
  level:
    root: INFO
    com.github.im.group.gui: DEBUG


spring:
  profiles: android
  jvm:
    args: -Djavafx.platform=ANDROID
  aot:
    enabled: true
#    reactor.netty: DEBUG
