im:
  download:
    directory: downloads  # 下载服务获取到的相对路径
  server:
    rest:
#      host: ${SERVER_HOST:http://localhost:8080}
      host: ${SERVER_HOST:http://192.168.3.22:8080}
    connect:
#      host: ${CONNECT_HOST:192.168.3.22}
      host: ${CONNECT_HOST:192.168.3.22}
      port: 8088

javafx:
  platform: DESKTOP
logging:
  level:
    root: INFO
    com.github.im.group.gui: DEBUG


spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:h2:file:./data/group-db;DB_CLOSE_DELAY=-1
#    url: jdbc:h2:file:${user.home}/data/im-db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: group
    password: group
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update


  jvm:
    args: -Djavafx.platform=desktop
#  aot:
#    enabled: true
#    reactor.netty: DEBUG
