im:
  server:
    rest:
      host: ${SERVER_HOST:http://localhost:8080}
    connect:
      host: ${CONNECT_HOST:localhost}
      port: 8088

javafx:
  platform: DESKTOP
logging:
  level:
    root: INFO
    com.github.im.group.gui: DEBUG


spring:
  jvm:
    args: -Djavafx.platform=desktop
#  aot:
#    enabled: true
#    reactor.netty: DEBUG
